### ISSUE TITLE
octet stream corruption from HTML filtering / script snippet injection

### ISSUE THREAD

**Issue by EdHartHub** [NanoAdblocker/NanoCore#95] opened 2018-01-20 20:48 UTC
NanoAdblocker makes all downloads from openload.co host unusable, sort of corrupt them. 

1) Takes a long time to finalize a download when %100 of download is already achieved (read below)**
2) Downloaded files are unusable and if rared they are unpackable or "damaged"

**I noticed that NanoAdblocker writes an extra script/html on top of every file "header" after finishing the download, makes them unrecognizable for their respective player/unpacker. I think the delay to finalizie a file is because of that; when Nano writes that extra information. I opened several of them in a HexEditor and all had that extra script/html comparing to original files. I don't have the same issue with uBlock Origin though, only NanoAdblocker with or without NanoDefender (disbaled uBlock).

Random file for you test, it won't play on your player ie: VLC
https://openload.co/f/Nh5g37kJ14Q/VID-20150703-WA0007.3gp.mp4

You can also upload your own created rar file to give it a try. Rar file header is more straight forward.

- Operating System and Version:  MS Windows 10 Pro
- Browser and Version: Mozilla FireFox 57.0.4 (64-bit)
- Nano Adblocker Version: 1.0.0.27 (absolute default settings)

**Comment by jspenguin2017** [comment] 2018-01-21 01:19
OK, this is probably caused by HTML filtering. You can rollback to the last version. 
Does this happen with latest dev version of uBO?

**Comment by EdHartHub** [comment] 2018-01-21 01:45
That's was my first Nano installation, would rather to wait for a newer version. 

I have uBO version 1.14.24 installed.

**Comment by jspenguin2017** [comment] 2018-01-21 01:47
Eh, it'll take time for me to investigate and report to gorhill, and chances are the next version of uBO will have the same problem...

**Comment by EdHartHub** [comment] 2018-01-21 01:58
uBO works fine now, will wait for your next release.

FYI, I just tried 1.0.0.26 and no issues.

**Comment by jspenguin2017** [comment] 2018-01-21 17:18
Does the *dev version* of uBO works fine?

**Comment by cubedj** [comment] 2018-01-21 17:39
the files are exact match with the latest uBO dev version (1.14.25.101)... (*I'm on Chrome)

**Comment by jspenguin2017** [comment] 2018-01-21 17:46
The filtering engine is exact match, yes (obviously there are differences elsewhere). So trying to wait it out will probably not going to work very well...

**Comment by EdHartHub** [comment] 2018-01-21 18:17
What are my options now? I'm pretty confused, I do have issues with Nano 1.0.0.27 (latest) and might have the same issues with uBO's next version as well. In both scenarios, for future, I have to stay with outdated versions. So what do you recommend?

**Comment by jspenguin2017** [comment] 2018-01-21 19:35
I recommend you to test on the dev version of uBO and file a bug report to gorhill. 
I'm a bit busy recently and it can take a while before I find time to trace and report this bug to upstream.

**Comment by cubedj** [comment] 2018-01-21 19:44
I should make it clear - what I meant was that when trying to download the file from openload.co with the latest uBO dev version enabled > there's no corruption and the files are exact match as if downloaded with all extesnions disabled... at least for me..

**Comment by jspenguin2017** [comment] 2018-01-21 20:08
I'll trace it later. Couldn't reproduce after a quick test.

**Comment by EdHartHub** [comment] 2018-01-21 21:32
Same here, as @cubedj reported, files remains intact using uBO dev version.

**Comment by jspenguin2017** [comment] 2018-01-21 21:36
It remains intact with Nano as well, which other extensions do you have?

**Comment by EdHartHub** [comment] 2018-01-21 21:56
I'm gonna upgrade to 1.0.027 and start to disabling my addons one by one and see the result. My addons list;

-Disconnect for Facebook (I Installed this one along with Nano yesterday, could be a prime suspect)
-Enhancer for YouTube
-FoxyTab
-Google search link fix
-I dont care about Cookies
-Nano Adblocker + Defender
-Popup BVlocker Ultimate
-PrintEdit WE
-SpeedDial FVD
-Tiny Todo
-Undo Close Tab
-X-Notifier

**Comment by EdHartHub** [comment] 2018-01-21 22:06
UPDATE: disabled every single addon on Firefox, even Nano Defender, the issue still exist.

Additionally I tired on my other system with brand new FireFox, same issue.

**Comment by cubedj** [comment] 2018-01-21 23:06
just for the sake of control - the **SHA1** of the test video file *VID-20150703-WA0007.3gp.mp4 from the link you sent is (or should be) **f8755f8ee61f09db6daf58689c6b26268b55ce3c** 
... if yours will be different even with another browser, then it would seem more like OS or HW (HDD or maybe some driver) issue...

**Comment by EdHartHub** [comment] 2018-01-21 23:17
It's not limited to the link, it was just an example from a very random search on google! The issue exists for every file that I've tried to download from openload.co with 1.0.0.27. Beside that, uBO and 1.0.0.26 doesn't reproduce the same issue, so it can't be OS or HW with two separate computers.

**Comment by jspenguin2017** [comment] 2018-01-21 23:41
I can't reproduce with latest Nano Adblocker. 
![image](https://user-images.githubusercontent.com/7283682/35200356-f895f84e-fec9-11e7-9992-6847519c46be.png)

**Comment by EdHartHub** [comment] 2018-01-22 03:55
Here is what I got; definitely the checksum created with 1.0.0.27 (also 1.0.0.28) is different with 1.0.0.26 for me. Both downloads with 1.0.027 and 1.0.0.28 are broken, while with 1.0.0.26 is not. Please pay attention to the file size as well. What did you use to calculate the checksum, the tool looks interesting.

PS: All addons were DISBALED when I downloaded them.

![01](https://user-images.githubusercontent.com/35639317/35204605-2cff32ac-fee4-11e7-82de-0a8e1529f848.jpg)

Files in a HexEditor 

![02](https://user-images.githubusercontent.com/35639317/35204619-48380f9e-fee4-11e7-8345-360929ea01bc.jpg)
![03](https://user-images.githubusercontent.com/35639317/35204620-48523d9c-fee4-11e7-9f91-5480756ab589.jpg)

Files in ASCII mode for better view

![04](https://user-images.githubusercontent.com/35639317/35204643-75b57966-fee4-11e7-8211-277de11a61aa.jpg)
![05](https://user-images.githubusercontent.com/35639317/35204644-75d4859a-fee4-11e7-9396-b0468a280fdb.jpg)

**Comment by EdHartHub** [comment] 2018-01-22 04:10
CORRECTION: I tried with uBO dev version again (1.14.25rc1) and it corrupted the file as well. I might not installed the dev version properly when I reported for the first time, sorry. I swicthed back and forth a few times to make it sure this time. Summary;

Nano 1.0.0.26 and uBO 1.14.24 download the file intact
Nano 1.0.0.27 (1.0.0.28) and uBO 1.14.25rc1 corrupt the file.

Do you want me to report to gorhill as well?

**Comment by jspenguin2017** [comment] 2018-01-22 04:13
Looks like HTML filtering. The MP4 octet stream is interpreted as HTML document. 
You definitely should report to gorhill. I cannot reproduce it. Did you touch browser flags? 

The tool is 7-Zip.

**Comment by EdHartHub** [comment] 2018-01-22 04:26
No, not recently at least (last two years). I would also suggest to change the title and remove "octet stream" since it corrupts ANY file and not just videos. My issues started basically with RAR files. It does same for rar too, like you said it injects script snippet to any file.

I'll go ahead and report tomorrow unless you ping him. I'm new in github, so don't know how to ping to be honest!

**Comment by KonoromiHimaries** [comment] 2018-01-22 04:31
@EdHartHub `@ + EdHartHub`
https://guides.github.com/features/mastering-markdown/

**Comment by jspenguin2017** [comment] 2018-01-22 13:20
Well, RAR files are octet stream as well. 
I pinged him, but his not responding. You should report to his repo if he doesn't respond  tomorrow.

**Comment by gorhill** [comment] 2018-01-22 13:57
Report on my repo if it's a uBO issue, i.e. if you can reproduce with uBO 1.14.25rc1. I wasn't able to reproduce on my side.

**Comment by gorhill** [comment] 2018-01-22 14:48
As per dev console, a `text/html` document is first served when clicking "Download", which the redirects to the actual `application/octet-stream` resource. However as said, I can't reproduce your issue, so even if I try a fix (filter only if status code === 200), I would have no idea whether it helps or not. So best is you report on my issue tracker and from there we explore the fix together.

**Comment by gorhill** [comment] 2018-01-22 15:06
It seems to me the issue could arise if one tries to inject a scriptlet into `oloadcdn.net`, but I can't find such filter.

**Comment by jspenguin2017** [comment] 2018-01-22 15:32
Well if it can be triggered by any filter, I'd consider it to be a engine bug. Filtering the root document element also cause hang https://github.com/NanoAdblocker/NanoCore/issues/90
I guess I need to add a master switch for HTML filtering, it'll be great if servers are all standard compliant, but unfortunately browsers are too flexible at handling server bugs.

**Comment by gorhill** [comment] 2018-01-22 15:42
> I'd consider it to be an engine bug.

Sure, nowhere did I suggest the opposite.

> Filtering the root document element also cause hang #90

And why is this not reported on my issue tracker?

**Comment by jspenguin2017** [comment] 2018-01-22 15:57
> And why is this not reported on my issue tracker?

Unlike this bug, filtering doc root is more than useless, although it's still kind of engine bug and should be fixed, but there is no rush in that so I didn't get to it yet. 
I brought it up here because it *might* be related as @EdHartHub said the download takes a long time to complete, a.k.a. hang.

**Comment by gorhill** [comment] 2018-01-22 19:04
> I'm gonna fully refresh my Firefox

Just try in a new profile first.

**Comment by EdHartHub** [comment] 2018-01-22 19:35
**IMPORTANT UPDATE:** The issue solved after refreshing my Firefox using "Refresh Firefox" option. 

@gorhill, I don't know if creating a new profile does the same as "Refresh Firefox" but I have a backup from my profile, so I can restore and create a new profile to test, I believe it's same thing.

Just before that, I checked my configuration "about:config" and found so many unnecessary flags from removed/outdated addon (some uninstalled/some disabled) and etc. As @jspenguin2017 pointed out earlier they could could be the culprit.

Btw, thank you all for your **prompt** help, and I'm truly sorry for the confusion I made. If anything else  I can do to help you guys, please fell free to ask. Thanks again.

**Comment by jspenguin2017** [comment] 2018-01-22 21:53
Yea, I was still unable to reproduce it. Since it's fixed on your side, I'd say this is caused by browser bug. Closing.

**Closed by jspenguin2017** 2018-01-22 21:53 UTC
