### ISSUE TITLE
Weird issue on Edge NanoAdblock - flashscore - cosmetic filtering

### ISSUE THREAD

**Issue by SpicBeanerMower** [NanoAdblocker/NanoCore#219] opened 2018-10-11 17:56 UTC

**Comment by jspenguin2017** [comment] 2018-10-11 18:56
Do you have a specific test link? Also, are you using InPrivate mode?

**Comment by SpicBeanerMower** [comment] 2018-10-11 20:16
I usually just go to www.flashscore.com which goes directly to football/soccer sport section. So I noticed this weird behavior because I like to check hockey/basketball and American Football and then saw sometimes it displayed the bet ads, and today I noticed that it was whenever I hit refresh or click different sports sections.

If I use specific sports flashscore.com/hockey on a blank tab, it seems to block things fine, doesn't show the bet365 image and all that. But seems like the panel doesn't show the numbers about cosmetic or javascript filters applied, just like 3rd pic shows. And then clicking on another sport like basketball, tennis or whatever then it seems like it shows the bet images, and while it is only cosmetic (apparently) it is annoying.

and no, no InPrivate mode, but I tested it just to see and it acts exactly the same.

**Comment by jspenguin2017** [comment] 2018-10-11 20:53
Can't reproduce on 1803, works flawlessly for me. 

Chances are 1809 broke something. I'll update once 1809 hits business branch and see what happens.

**Comment by jspenguin2017** [comment] 2018-10-11 20:57
Or if someone who is on 1809 wants to help me track down the problem. Marking as available.

**Comment by PeteAtGH** [comment] 2018-10-12 23:44
Hi, tried on several different Surfaces, all on 1809 17763.55 and cannot reproduce any of the mentioned errors on Edge but Opera (Chromium) became completely unusable on them, so decided to remove Opera for good.

**Comment by SpicBeanerMower** [comment] 2018-10-13 00:59
Well, I tested on a 3rd computer and it seems to behave the same. I don't even know if the other two computers even have the Tuesday update. I could have tested it on a 4th computer outside home but that computer doesn't have Win10 1809.

What I notice it's that it is a general issue, the adblocker function seems to work file since console says connections have been blocked by the extension, but not the cosmetics, since I noticed I got ads displayed on Bing as well that are not being hidden by the filtering and then the Picker mode doesn't work anymore like happens on flashscore. Of course on Flashscore the issue was easier to spot and test, on Bing you have to search for something that can show ads and then go to page 2 and sometimes the ads would just show.

So, I don't know what's going on, because I installed Adguard extension again and it seems to work fine. when I tested it since I installed it to check a website that I use it couple time but it wasn't loading the player with Nano, so I checked to see if it was Nano the problem, but it was a small rule breaking the player on uBlock Filters  Privacy, not Nano itself. I got the same issue on Adguard after enabling some rules. So I tested Adguard about the cosmetics issue and and seemed to work fine all the time unlike Nano.
It's technically not a deal breaker since it is just the cosmetics filtering hiding stuff but not really doing anything special, the adblocker function, what matters is working fine, but it's just weird 3 computer and same behavior.
I will see if I can update the other computer (tell the person to do it) like see if it is available since what happened about the deletion of files behavior thing, and see if that computer somehow doesn't do the same.

**Comment by jspenguin2017** [comment] 2018-10-13 01:13
Can someone check the background console?

**Closed** 2018-10-13 04:11 UTC
Labels: available
