### ISSUE TITLE
3rd party filters keep resetting every update? [Getting unchecked]

### ISSUE THREAD

**Issue by JourneyOver** [NanoAdblocker/NanoCore#49] opened 2017-12-16 15:31 UTC
### Describe the issue (Required)

3rd party filters keep getting reset every time there is an update.. The only filter that doesn't get reset/unchecked is "Nano Defender Integration"

### Environment (Required)

- Operating System and Version: Windows 10 x64 bit, version 1709 latest updates
- Browser and Version: Chrome 62.0.3202.94
- Nano Adblocker Version: 1.0.0.13

#### Your filter lists (Required)

Well seeing as how my 3rd party filters keep getting reset I guess none...

#### Your custom filters (Required if you have any)
```
! Add exception to EasyList rule to let YouTube track video progress
@@||s.youtube.com/api/stats/watchtime*

! Block YouTube Gaming Event Promo
youtube.com##div[id^="gaming-event-promo-overlay"]

! Block YouTube end cards
##.ytp-ce-video

! 1/1/2017, 3:44:29 AM http://www.deviantart.com/notifications/#view=watch
www.deviantart.com##.active.gogo-upsell

! 3/16/2017, 8:55:21 PM https://www.reddit.com/
www.reddit.com##.recommended-link

! 11/15/2017, 6:09:05 PM https://www.reddit.com/
||www.reddit.com/chat/minimize$subdocument

! 7/28/2017, 7:25:55 AM https://www.reddit.com/user/Static_Love/saved
www.reddit.com##.profilebetabar.infobar

! 7/23/2017, 2:01:00 AM https://www.iptorrents.com/t
www.iptorrents.com##.cfapps-welcome-bar

! 12/14/2017, 3:42:22 AM https://metagamerscore.com
metagamerscore.com##.ad_wide_ss
metagamerscore.com###aff_box > center
```

**Comment by jspenguin2017** [comment] 2017-12-16 15:44
Do you lost other settings?

**Comment by jspenguin2017** [comment] 2017-12-16 15:46
Might be a race condition, are you on a SSD? 
I updated Nano Defender to be more tolerant on slow devices. 
I just can't reproduce this though, but I think I have an idea where the problem is coming from. I thought 2.5 seconds is enough for even the slowest device to initialize.

**Comment by JourneyOver** [comment] 2017-12-16 15:47
@jspenguin2017 nope it's just 3rd party filters that seem to get lost for some reason. Never seen it happen before when I used uBlock, but it just recently started doing it.

Yes I'm on an SSD.

**Comment by jspenguin2017** [comment] 2017-12-16 15:49
Can you post your spec?

**Comment by JourneyOver** [comment] 2017-12-16 15:59
Operating System: Windows 10 Pro 64-bit (10.0, Build 16299) (16299.rs3_release.170928-1534)
Processor: AMD FX(tm)-6350 Six-Core Processor              (6 CPUs), ~4.2GHz
Memory: 8192MB RAM
Graphics: NVIDIA GeForce GTX 760

Hard Drives & SSD:
PNY CS1311 240GB SSD
SAMSUNG HD 400GB
and 2 Western Digital 1TB HD

anything else ya need?

**Comment by jspenguin2017** [comment] 2017-12-16 16:00
That's weird, the race condition never occur for me... 
I'll add a flag to make it absolutely secure.

**Comment by jspenguin2017** [comment] 2017-12-16 16:10
I have a temporary measure in place, which should be good enough until a proper fix can be landed.

**Comment by jspenguin2017** [comment] 2017-12-16 16:11
New integration logic (please review): 
```js
vAPI.messaging.onNanoDefenderActivated(function(msg) {
    if ( msg === 'Nano Defender Enabled' ) {
        var performConfiguration = function() {
            if ( nano.selectedFilterLists.includes('nano-defender') ) {
                return;
            }
            
            // Make sure to keep this fixed:
            // https://github.com/NanoAdblocker/NanoCore/issues/49
            if ( !nano.selectedFilterListsLoaded ) {
                setTimeout(performConfiguration, 500);
                return;
            }
            
            nano.saveSelectedFilterLists([ 'nano-defender' ], true);
            var dispatchReload = function() {
                if ( nano.loadingFilterLists ) {
                    setTimeout(dispatchReload, 500);
                } else {
                    nano.loadFilterLists();
                }
            };
            dispatchReload();
        };
        performConfiguration();
    }
});
```

**Comment by JourneyOver** [comment] 2017-12-16 16:41
I'm currently not at home right now so I can't test anything as I'm not able to be at my computer.

I dunno exactly when I'll be home but I'll test things out when I get the chance.

**Comment by JourneyOver** [comment] 2017-12-16 19:35
@jspenguin2017 okay I'm home now and at my computer, how can I test the above logic?

Though idk how to really test it either as it only seems to happen when there is an update... and I should make mention though I believe I said it in the first post, whenever I lose all my 3rd party filters, the only one that stays enabled and not lost is "Nano Defender Integration" though I believe that is due to how you have made it always enabled by default while any other 3rd party is not enabled by default.

**Comment by jspenguin2017** [comment] 2017-12-16 20:16
I guess the only way is to read the code 3 times and hope it's good...

**Comment by JourneyOver** [comment] 2017-12-16 20:54
Haha only time will tell I guess xD

**Closed** 2017-12-17 01:27 UTC
Labels: fixed

**Comment by jspenguin2017** [comment] 2017-12-17 01:45
I hope this fixes this problem for good. I'm not super familiar with uBO's source code, it'll get better.

**Comment by JourneyOver** [comment] 2017-12-19 19:27
So far haven't had any problems yet after 3 days, so looks like this may be actually fixed.
