### ISSUE TITLE
I can not find the blocklist URL?

### ISSUE THREAD

**Issue by slrslr** [NanoAdblocker/NanoCore#79] opened 2018-01-03 09:52 UTC
Hello,

i have uBlock Origin installed and in this repository i can not find the file with filters/rules that i can use in my uBlock.

What is the URL please? Can it be mentioned in README?

Thank You

**Comment by jspenguin2017** [comment] 2018-01-03 16:19
If you want Nano's filters, you have to find them in `assets.json`. Those filters will may not work as expected with uBO out of the box. 
See the documentation for more detail: https://github.com/NanoAdblocker/NanoCore/blob/master/Notes/FilterIncompatibility.MD

**Comment by jspenguin2017** [comment] 2018-01-03 23:49
I assume this is a duplicate of https://github.com/NanoAdblocker/NanoCore/issues/81
Let me know if you have further concerns.

**Closed** 2018-01-03 23:49 UTC
Labels: question
