### ISSUE TITLE
Nano Adblocker is spending > 70ms during requestAnimationFrame

### ISSUE THREAD

**Issue by jrmuizel** [NanoAdblocker/NanoCore#311] opened 2020-03-02 22:41 UTC
Nano Adblocker is spending > 70ms during requestAnimationFrame. This will have a very negative impact on performance.

Here's a link to a profile showing the problem: https://perfht.ml/32Hyqxo

**Comment by jrmuizel** [comment] 2020-03-02 22:43
The bulk of the time is spent doing selector matching on a bunch of selectors.

**Comment by jspenguin2017** [comment] 2020-03-02 23:05
Can't reproduce, need a test link.

**Comment by jrmuizel** [comment] 2020-03-03 17:36
The user that made the profile says that it was on facebook or reddit. I've asked for more details.

**Comment by jspenguin2017** [comment] 2020-03-03 18:08
I tested Facebook on my four years old tablet, the animation frame handler takes up to 15 ms. Note this only happen from time to time, not every animation frame. The website runs pretty smoothly. 
![image](https://user-images.githubusercontent.com/7283682/75805371-f2bc3e80-5d3e-11ea-8f7f-ee93df214447.png)

**Comment by jspenguin2017** [comment] 2020-03-03 18:18
I am going to close this since you did not fill the template. Keep in mind that I do not maintain the Firefox build. If you can reproduce the issue on Chrome, feel free to open another issue with completed template and detailed reproduction steps.

**Closed by jspenguin2017** 2020-03-03 18:18 UTC
Labels: question

**Comment by gorhill** [comment] 2020-03-06 15:41
@jrmuizel 

From what I can see, the bulk of the time is spent enforcing procedural cosmetic filters. The user would need to disclose what are these procedural cosmetic filters -- filter list authors are aware that these sort of filters have to be used parsimoniously. Facebook's site however makes it difficult for content blockers to do their job and last time the site required the use of complex procedural filters.

Also, there the procedural cosmetic filters code will disable procedural cosmetic filters which are found to be performance bottleneck. As per profiling, the procedural filters uses 1,332 / 20,000ms or ~6.5%, probably below the threshold of what is considered a performance bottleneck.

Now for the specific profiling results you shared, we really need more information as to how the user configured his content blocker (which is essentially at its core uBlock Origin) -- I don't think it's normal for the code to spend so much time in `querySelectorAll()` -- this suggests some bad filters are being in use. For instance, when I expand `Element.querySelectorAll` in the profiler,  I see a lot of entries like so:

![a](https://user-images.githubusercontent.com/585534/76098134-e92d1380-5f96-11ea-9bef-f95cdf6521d7.png)

These are not part of the default filter lists, and this suggests the user created too many procedural filters.

**Comment by gorhill** [comment] 2020-05-20 16:24
Related bugzilla issue: <https://bugzilla.mozilla.org/show_bug.cgi?id=1633409>.
