### ISSUE TITLE
include "HTTPS Everywhere" in to nano adblocker

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#139] opened 2018-03-18 03:14 UTC
`HTTPS Everywhere` extension is now incompatible with nano adblocker and i don't have any alternative for that
https://github.com/EFForg/https-everywhere/issues/14867

i think this is most safe and useful option to include mechanism `force https` per specified site in to nano adblocker

thanks.

**Comment by jspenguin2017** [comment] 2018-03-18 03:53
Probably won't fix. Even if I add an URL rewriting mechanism, it probably won't be able to handle the full HTTPS Everywhere logic.

**Comment by jspenguin2017** [comment] 2018-03-18 03:54
As a rule of thumb, any request like merging in another extension will probably be rejected.

**Closed** 2018-03-18 03:59 UTC
Labels: wontfix

**Comment by cucumbur** [comment] 2018-04-11 20:43
So for someone who would like to use both... is there a way to get around it on an individual basis via some editing of filters / scripts or different extensions?

**Comment by jspenguin2017** [comment] 2018-04-11 21:44
You can whitelist the tracking script if you think that helps your privacy, I will NOT fix this, period. I don't care how the reviews are, I only check them like once a week to collect bug reports. 

Alternatively, you can simply ignore the warning. With Chromium, you can suppress the error by unchecking "collect errors" in the extension manager.

**Comment by cucumbur** [comment] 2018-04-11 22:40
Okay, you missed the point (actually, I don't think you read it far enough to get the point). I was trying to be diplomatic because I think OP's idea is bad but the issue is being taken seriously by multiple other addons as compatibility isn't a one sided situation most of the time, and privacy extensions are used in conjunction.

But now it's just obvious this is the uBlock shit all over again. Adblock, ublock, nanoblock, everyone ends up fucking up a tool people appreciate by greed or by letting OSS maintenance become a stage where issues are personal attacks. Time to move to pihole

**Comment by jspenguin2017** [comment] 2018-04-11 23:25
Look, if you think you have a good solution for the problem then just fork it and maybe PR later. The situation is clearly not a problem on my (nor gorhill's) side, if you think you can make it better, just PR and I (and gorhill) can review your changes and discuss further. If all you got is the excuse that you don't know how to code then shut up and accept the decision of the main developers. 

Keep in mind that showing your recommendations are good is not always straightforward, sometimes you need to split off a fork to gain momentum. Words have no weight, actions do. 

There are times when requests are just ridiculous as per common sense of developers, and none of us got time to teach you how to code. Extension only die when the developers no longer use them. No matter how many users there are, if the developers are not using it themselves, it won't be maintained for long. 

You are free to use what you want, that's your freedom. 1 developer is more valuable than 1 million users. There are extensions with less than 500 users that are still actively maintained and there are extensions with millions of users but are abandoned. If you want to be part of the problem and not the solution, please leave.
