### ISSUE TITLE
[feature suggestion] Add subscriptions to lists of filterlists

### ISSUE THREAD

**Issue by elypter** [NanoAdblocker/NanoCore#60] opened 2017-12-23 06:25 UTC
with the growing numbers of filterlists for all sorts of purposes and from many different sources and a better publicity thanks to filterlists.com it is becoming quite some effort to find the right set of filterlists. it would make life a bit easier for new people if they could subscribe to a metalist which contain a certain set that suits their needs without having to find and test each of those filterlists. such subscriptions could be implemented as super sections of which all the default lists are one section and every subscription is another. just like the original section each of them should have subsections.

**Comment by jspenguin2017** [comment] 2017-12-23 16:18
All the filters in the third party settings tab are deemed somewhat good quality, and is grouped by what it does, for example, if you want to get rid of annoyance, just check every annoyance filter. 
If you just want something that block ads and some tracking scripts, the default works well.

**Comment by elypter** [comment] 2017-12-23 17:49
what i mean should be similar to addon collections on amo or collections on instructables. any user can make lists of their favorite addons or projects to fit a certain type of user. so you could make some sort of child-friendly collection which contains all non-experimental adblockers, anti scamming and porn filters or you create a profile for old computers which contains adblockers with some more agressive filters and removal of all sorts of annoyances and bloat at the risk of occasionally breaking something. one for very privacy focused people and so on. each of those metalists would contain filters from multiple categories.

with the amount of lists that are currently on the default page the current system is sufficient but if you look at [filterlists.com](https://filterlists.com) the number of lists becomes too large without having to invest considerable amounts of time reviewing each of them to not add any bad ones and at the same time not to miss out on any of the good ones and to find everything you personally want. it wouldbe a great help if you are sitting at your grandmas computer and you could just add a single metalist that takes care of everything and tell her that you removed all the bad stuff from the internet and not having to fiddle around for half an hour and having to fear you added something that might make some of the websites unusable.

**Comment by jspenguin2017** [comment] 2017-12-23 18:17
Like a filter registry? Yes, it'll come with the new dashboard. I'll close this as duplicate then.

**Comment by jspenguin2017** [comment] 2017-12-23 18:17
Duplicate of #33

**Closed by jspenguin2017** 2017-12-23 18:17 UTC
Labels: duplicate
