### ISSUE TITLE
[Enhancement] Support block html autoplay on injector

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#39] opened 2017-12-14 13:47 UTC
![2017-12-14 14_44_40-nano adblocker - chrome web store](https://user-images.githubusercontent.com/5884000/33995184-78cbb734-e0dd-11e7-86d9-c6b32c945818.png)
`https://chrome.google.com/webstore/detail/nano-adblocker/gabbbocakeomblphkmmnoamkioajlkfo`

**Comment by jspenguin2017** [comment] 2017-12-14 15:06
I definitely saw that, any idea on how to implement it?

**Comment by uBlock-user** [comment] 2017-12-14 22:33
Chrome already has Autoplay Policy via chrome://flags

**Comment by mat41997** [comment] 2017-12-18 04:39
![2017-12-18 05_34_00-autoplaystopper dla chrome google nie lubi zewnetrznych adblockow - dobreprogra](https://user-images.githubusercontent.com/5884000/34090173-50e848ba-e3b5-11e7-9ee6-53b3c42b15da.png)
`https://www.dobreprogramy.pl/AutoplayStopper-dla-Chrome.-Google-nie-lubi-zewnetrznych-adblockow,News,84859.html#komentarz-2297043`

r1234 has said
> Czasami Chrome przepuszcza wideo (dla porówania Firefox przy włączonej blokadzie prawie nigdy). Teraz Ci nie powien na jakich stronach Chrome przepuszcza, bo to jakiś czas temu porównywałem, jeszcze kiedy używałem "Disable HTML5 Autoplay" (ostatnio wymieniłem to rozszerzenie na AutoplayStopper).

"somewhere chrome has passed the video"

**Comment by LuaTenshi** [comment] 2017-12-19 01:13
I made a quick script for stopping autoplaying videos but it can probably be enhanced and cleaned up allot. Also this is a userscript made in and for Tampermonkey not sure how well it will work else where and or what changes would need to be made.

```Javascript
// ==UserScript==
// @name         Video Element Pause
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       LuaTenshi
// @include      *://*
// @exclude      /^https?://(www\.|)youtube\.com/.*$/
// @exclude      /^https?://(www\.|)twitch\.tv/.*$/
// @exclude      /^https?://(www\.|)googlevideo\.com/.*$/
// @exclude      /^https?://(www\.|)vimeo\.com/.*$/
// @exclude      /^https?://(www\.|)vid\.me/.*$/
// @exclude      /^https?://(www\.|)dailymotion\.com/.*$/
// @exclude      /^https?://(www\.|)veoh\.com/.*$/
// @exclude      /^https?://(www\.|)netflix\.com/.*$/
// @exclude      /^https?://(www\.|)liveleak\.com/.*$/
// @exclude      /^https?://(www\.|)gelbooru\.com/.*$/
// @exclude      /^https?://danbooru\.donmai\.us/.*$/
// @exclude      /^https?://(www.|)kissanime\.com/.*$/
// @exclude      /^https?://(www.|)kisscartoon\.me/.*$/
// @exclude      /^https?://(www.|)kissanime\.to/.*$/
// @exclude      /^https?://(www.|)kissasian\.com/.*$/
// @exclude      /^https?://(www.|)kissmanga\.com/.*$/
// @exclude      /^https?://(www.|)readcomiconline\.to/.*$/
// @exclude      /^https?://(www.|)kissanime\.ru/.*$/
// @exclude      /^https?://(www.|)kisscartoon\.se/.*$/
// @exclude      /^https?://(www.|)kissasian\.ch/.*$/
// @exclude      /^https?://(www.|)kimcartoon\.me/.*$/
// @grant        none
// @run-at       document-idle
// ==/UserScript==

function restore(vid, observer){
    if ( !vid.restored ){
        observer.disconnect();
        vid.onplaying = vid.oldOnplaying;
        vid.oldOnplaying = null;
        vid.restored = true;
    }
}

(function() {
    'use strict';
    var vids = document.getElementsByTagName('video');

    for ( var i = 0; i < vids.length; i++ ){
        var vid = vids[i];

        var obj = {
            oldOnplaying: vid.oldOnplaying,
            onplaying: vid.onplaying,
            preload: 'none'
        };

        var obsettings = {
            attributes: true,
            attributeFilter: ['preload'],
            childList: false,
            characterData: false
        };

        vid.oldOnplaying = obj.onplaying;
        vid.preload = obj.preload;
        vid.setAttribute('preload', obj.preload);

        vid.onplaying = function(){
            vid.pause();
        };

        var observer = new MutationObserver(function(event){
            observer.disconnect();
            var target = event[event.length-1].target;

            target.preload = obj.preload;
            target.setAttribute('preload', obj.preload);

            observer.observe(vid, obsettings);
        });

        observer.observe(vid, obsettings);
        vid.addEventListener('click', function(){restore(vid, observer);}, false);
        vid.parentNode.addEventListener('click', function(){restore(vid, observer);}, false);
    }
})();
```

**Comment by jspenguin2017** [comment] 2017-12-19 01:46
It's long, so I folded it, click the triangle to expand it. 
Since it's grant none, it will "just works", however, using the right tool for the job is probably better. Since it is a Tampermonkey script, why not use Tampermonkey?

**Comment by LuaTenshi** [comment] 2017-12-19 02:40
@jspenguin2017 Thanks, I'm not very familiar with Markup, else I would have done that myself. Updated the code a bit.

Also I know it "just works" with Tampermonkey however this issue is about having an injectible script that will block autoplaying video games on target sites and I thought that my userscript would help either you or any one else who's interested in contributing get started on making something. ^^;

**Comment by jspenguin2017** [comment] 2017-12-19 02:43
I mean all script snippets are like "grant none", which would work with Nano, just I think it makes more sense to use Tampermonkey or Violentmonkey for that.

**Comment by LuaTenshi** [comment] 2017-12-19 02:46
Ah okay, at least I contributed something.

Off Topic: Fo you prefer Violentmonkey over Tampermonkey? I've been using Tamper forever but hold about Violent only recently.

**Comment by jspenguin2017** [comment] 2017-12-19 03:33
I prefer wrapping my Userscripts in an extension. Both TM and VM have some race condition, I think TM has some hacks that make its scripts to inject faster, but real extensions are guaranteed to run on the real `document-start`. Doing so also makes them really lightweight. And I have access to powerful extension APIs such as management. 
![image](https://user-images.githubusercontent.com/7283682/34139456-1ba5e3f6-e432-11e7-950e-b84106af6ed3.png)

Why not try both out and see which one you like?

**Comment by LuaTenshi** [comment] 2017-12-19 06:22
Your method actually sounds interesting but it sounds painful to have to rezip every time. 
Do you have a Discord server/account so that we can talk without hijacking this issue?

**Comment by jspenguin2017** [comment] 2017-12-19 13:45
I don't have Discord. I haven't changed my extension in the past 3 months, if you find yourself changing it often then no, that's probably not going to work for you.

**Comment by jspenguin2017** [comment] 2017-12-22 19:34
@LuaTenshi Actually, you may not need to re-zip it every time, for one, you can have a build script to zip and push that automatically, otherwise, if you are using Chromium, you can load developer mode extensions and it will stay. For Chrome on Windows and macOS, Google put in some extra security and it's a pain to use unpacked extensions. 

Now back on topic: I don't see a reasonable way to block auto-play with script snippet. Google is putting that in Chrome soon, so I guess I'll flag this as wontfix.

**Comment by jspenguin2017** [comment] 2017-12-27 16:42
Nano is available on Firefox too. Closing.

**Closed by jspenguin2017** 2017-12-27 16:42 UTC
Labels: wontfix

**Comment by elypter** [comment] 2017-12-27 18:32
@LuaTenshi 
thats a cool userscript. you should put it on greasyfork

**Comment by LuaTenshi** [comment] 2017-12-27 20:10
@elypter If I knew for sure that it would work on even the toughest of sites I'd put it on greasyfork but sadly I'm not sure on how to get it working on places like Twitch etc...

<details>
```Javascript
// ==UserScript==
// @name         Video Element Pause
// @namespace    http://tampermonkey.net/
// @version      0.2
// @description  try to take over the world!
// @author       LuaTenshi
// @include      *://*
// @exclude      /^https?://(www\.|)youtube\.com/.*$/
// @exclude      /^https?://(www\.|)twitch\.tv/.*$/
// @exclude      /^https?://(www\.|)googlevideo\.com/.*$/
// @exclude      /^https?://(www\.|)vimeo\.com/.*$/
// @exclude      /^https?://(www\.|)vid\.me/.*$/
// @exclude      /^https?://(www\.|)dailymotion\.com/.*$/
// @exclude      /^https?://(www\.|)veoh\.com/.*$/
// @exclude      /^https?://(www\.|)netflix\.com/.*$/
// @exclude      /^https?://(www\.|)liveleak\.com/.*$/
// @exclude      /^https?://(www\.|)gelbooru\.com/.*$/
// @exclude      /^https?://danbooru\.donmai\.us/.*$/
// @exclude      /^https?://(www.|)kissanime\.com/.*$/
// @exclude      /^https?://(www.|)kisscartoon\.me/.*$/
// @exclude      /^https?://(www.|)kissanime\.to/.*$/
// @exclude      /^https?://(www.|)kissasian\.com/.*$/
// @exclude      /^https?://(www.|)kissmanga\.com/.*$/
// @exclude      /^https?://(www.|)readcomiconline\.to/.*$/
// @exclude      /^https?://(www.|)kissanime\.ru/.*$/
// @exclude      /^https?://(www.|)kisscartoon\.se/.*$/
// @exclude      /^https?://(www.|)kissasian\.ch/.*$/
// @exclude      /^https?://(www.|)kimcartoon\.me/.*$/
// @grant        unsafeWindow
// @run-at       document-start
// ==/UserScript==

const SafeAutoPlay = true; // If this is enabled be sure to click in the middle of the video, as this works best.

function pause(vid, noevent, extend){
    if( vid && vid.pause && vid.load ){
        vid.pause();
        vid.preload = 'none';
        vid.autoplay = null;
        vid.setAttribute('preload', 'none');
        vid.setAttribute('autostart', 'false');
        vid.removeAttribute('autoplay');

        if( noevent !== true ){
            vid.addEventListener('canplay', function(e){
                e.preventDefault();
                pause(e.target, true);
            }, {once: true, capture: true});
        }
    }
}

function play(vid, x, y){
    var box = vid.parentNode && vid.parentNode.getBoundingClientRect() || vid.getBoundingClientRect();
    if( box && (x <= box.width && x >= box.x) && (y <= box.height && y >= box.y) ){
        vid.setAttribute('autoplay', 'true'); vid.play();
        vid.addEventListener('canplay', function(e){ e.target.play(); }, {once: true, capture: true});
        console.log('SafeAutoPlay Started: \n\t', vid);
    }
}

function restore(vid, observer, event){
    if ( !vid.____restored ){
        console.log('RESTORING: ', vid);
        pause(vid, 'auto');
        observer.disconnect();
        vid.onplaying = vid.oldOnplaying;
        vid.oldOnplaying = null;
        vid.removeAttribute('autostart');
        vid.____restored = true;
        if( event && SafeAutoPlay ){ play(vid, event.clientX, event.clientY); }
    }
}

function init() {
    'use strict';
    var vids = document.getElementsByTagName('video');

    for ( var i = 0; i < vids.length; i++ ){
        var vid = vids[i];

        var obsettings = {
            attributes: true,
            attributeFilter: ['preload'],
            childList: false,
            characterData: false
        };

        vid.oldOnplaying = vid.onplaying;
        vid.onplaying = function(){vid.pause();};
        pause(vid);

        var observer = new MutationObserver(function(event){
            observer.disconnect();
            var target = event[event.length-1].target;
            pause(target || vid);
            observer.observe(vid, obsettings);
        });

        observer.observe(vid, obsettings);
        setTimeout(function(){
            window.addEventListener('click', function(event){restore(vid, observer, event);}, {once: true, capture: true});
        },500);
    }
}

document.addEventListener('DOMContentLoaded', init);
document.addEventListener('DOMNodeInserted', function(e){
    var el = e.target;
    if (el.nodeName == "VIDEO"){
        console.log('Attempting to pause: \n\t',el);
        pause(el);
    }
}, false);
```
</details>

**Comment by elypter** [comment] 2017-12-27 20:50
its not perfect but i think it would still help people. for the 2 sites i was opening since installing it worked in both cases. those were tagesschau.de and hooktube.com (i dont mind autoplay on those sites but it worked as intended). if yu dont want to release it on greasyfork yet you can just put it on github too. i also have 2 userscripts on github that do not work perfectly. they are also easy to install if you have [INSTALL USER SCRIPT](https://greasyfork.org/de/scripts/6456-install-user-script)

**Comment by grand-lotus-iroh** [comment] 2018-02-02 05:03
So just to double-check, the best way to disable autoplay is using script or go into browser experimental features? gonna check out the script b/c i know the experimental feature is junk and doesn't work that well.. just test it out on cnet for example.

**Comment by KonoromiHimaries** [comment] 2018-02-22 17:39
html5 video autoplay blocker
`https://greasyfork.org/pl/scripts/30271-html5-video-autoplay-blocker`

do not block auto-play on this site
`https://eurosport.interia.pl/raporty/raport-pjongczang-2018/wideo/video,vId,2476144`

any idea for that?

**Comment by jspenguin2017** [comment] 2018-02-22 17:45
It uses `MutationObserver`, where I question its reliability.

**Comment by KonoromiHimaries** [comment] 2018-02-23 16:28
can't block auto-play on this site
`http://www.superstacja.tv/wiadomosc/2018-02-23/prezydent-tarnobrzega-z-korupcyjnymi-zarzutami/`

**Comment by hawkeye116477** [comment] 2018-02-23 21:23
I see that AdGuard has some rules to block autoplay.

```
bloomberg.com#%#AG_onLoad(function() { document.body.innerHTML = document.body.innerHTML.replace(/data-autoplay="true"/g, 'data-autoplay="false"'); });
azaku-anime.com#%#AG_onLoad(function() { document.body.innerHTML = document.body.innerHTML.replace(/autoPlay=1/g, 'autoPlay=0'); });
dailypost.co.uk#%#AG_onLoad(function() { setTimeout(function() { var e = document.querySelector('span.autoplay-cancel'); if (e) e.click(); }, 3300); });
```

**Comment by jspenguin2017** [comment] 2018-02-23 21:45
@hawkeye116477 
That code quality is beyond unacceptable.

**Comment by KonoromiHimaries** [comment] 2018-06-03 22:28
@jspenguin2017
