### ISSUE TITLE
There's one or more big bugs/oversights in the !#include tag

### ISSUE THREAD

**Issue by DandelionSprout** [NanoAdblocker/NanoCore#239] opened 2019-01-28 18:11 UTC
### Describe the issue (Required)

This one is going to be difficult for others to properly test, and for me to explain, but I'll try.

As the maintainer of ~30 lists for adblockers, I have on occasions made modular compilations of them with the `!#include` tag (An early example that is *not* affected by the problem I'll describe, being [this](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/YouTubeYetEvenMorePureVideoExperience.txt).)

While making a modular compilation for [theel0ja](https://github.com/theel0ja/ubo-recommendations/issues/1) called *Annoying Banners And Overlays* (The current version of which is [here](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyingBannersAndOverlays.txt)), I ran into a problem, in which it was impossible for me to add `!#include stayingonbrowser/Staying%20On%20The%20Phone%20Browser` (for the purposes of embedding [*Staying On The Phone Browser*](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/stayingonbrowser/Staying%20On%20The%20Phone%20Browser)) to the compilation without breaking it, even though this is how lists from subfolders are meant to be embedded.

After half an hour of testing, I was able to rule out things like spelling errors or folder misplacements, and instead found the issue was related to how *Staying On The Phone Browser* itself was embedding an extension from the same folder as itself, because `!#include` doesn't allow embedding lists that are higher up in the folder tree, for some reason.

Because *Staying On The Phone Browser* was embedding a list that was in the same subfolder as itself, thus it was embedding `!#include StayingOnThePhoneBrowser-uBOExtension.txt` with no mention of a subfolder; whereas *Annoying Banners And Overlays* was embedding *Staying On The Phone Browser* from a subfolder; caused a bug where *Annoying Banners And Overlays* tried looking for *StayingOnThePhoneBrowser-uBOExtension.txt* in the main folder, causing an inability to find it and breaking the ability to load *Annoying Banners And Overlays*.

### Screenshots (Required)

I am honestly unsure what I should be taking a screencap of in this case, so I'll skip this for now.

### Screenshot of console (Required, press `F12` to open the console)

Not applicable.

### URLs where this issue occurs (Required if applicable)

https://github.com/DandelionSprout/adfilt

### Reproduction Steps (Optional if trivial)

1) Make three lists with some sort of content in them, no matter how little.
2) In a Git or in a server's file tree, place List A in one folder, then make a subfolder in that folder, and place List B and List C in the subfolder.
3) Make List B embed List C through `!#include ListC`.
4) Try to make List A embed List B though `!#include subfolder/ListB`.
5) See that loading List B in Nano Adblocker works as it should, whereas loading List A is broken.

### Anything else you believe to be useful (Optional)

My personal opinion, is that the `!#include` tag is too strict on which lists that can be used with it, and that it's unfair that it completely breaks the list if even one letter in the embedded filename is wrong. I'd be in favour of loosening up which lists that can be embedded, and to make it so that a list does not break when an embedded list can't be found.

#### Environment (Required)

- Operating System and Version: Windows 10 October 2018 Update (Most recently installed update: KB4480116)
- Browser and Version: Google Chrome 71.0.3578.98 64-bit
- Nano Adblocker Version: 1.0.0.86
- Nano Defender Version (Optional if you are not using it): 15.0.0.89

#### Your filter lists (Required)

Not applicable, as far as I can determine.

#### Your custom filters (Required if you have any)

Not applicable.

**Comment by jspenguin2017** [comment] 2019-01-29 01:22
Does this affect upstream?

**Comment by jspenguin2017** [comment] 2019-01-29 02:54
I see that there's a slight oversight when it comes to resolving the path when a subfilter includes another filter. The path is resolved from the main filter, so if in filter B, the directive is `!#include subfolder/ListC` then it works. 

@gorhill FYI.

**Comment by gorhill** [comment] 2019-01-29 04:18
By design, I'm sure I explained this somewhere. When going up, there is no guarantee that the resource is still under control of the owner. GitHub is a good example.

**Comment by gorhill** [comment] 2019-01-29 13:08
https://github.com/gorhill/uBlock/issues/3331#issuecomment-354554069

**Comment by gwarser** [comment] 2019-01-29 13:31
14:30:56.994
XHRGEThttp://127.0.0.1:8080/top.txt?_=215106
[HTTP/1.0 200 OK 21ms]

14:30:57.034
XHRGEThttp://127.0.0.1:8080/subfolder/a.txt?_=215106
[HTTP/1.0 200 OK 6ms]

14:30:57.114
XHRGEThttp://127.0.0.1:8080/b.txt?_=215106
[HTTP/1.0 404 File not found 2ms]

**Comment by gorhill** [comment] 2019-01-29 13:37
@gwarser Thanks for the explanation, I understand now.

**Closed** 2019-01-30 01:37 UTC
Labels: bug, fixed upstream
