### ISSUE TITLE
add more option for filtering filters in filter list

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#248] opened 2019-02-22 08:39 UTC
### Describe the issue (Required)

e.g, 
- add button to see only active/deactive filters - this setting will be usefull for remove double rules
- add button on/off to better see description text <https://github.com/NanoAdblocker/NanoCore/issues/162>

### Screenshots (Required)

![2019-02-22-nano podglad zasobu](https://user-images.githubusercontent.com/5884000/53229960-da263c80-3685-11e9-90bd-55599ed5b0d3.png)

**Comment by jspenguin2017** [comment] 2019-02-23 02:15
> this setting will be usefull for remove double rules

Which rule is active is not stored. The compiler will throw out duplicate rules on the fly. 

> add button on/off to better see description text #162

Eh... Duplicate of #162 ?

**Closed by jspenguin2017** 2019-02-23 02:15 UTC
